### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by ghost** [HITMANek210/Aimware-Online-Radar#11]
i want to add dangerzone map to it what should i do

**Comment by HITMANek210** [comment]
If you would like to add dangerzone map to the script first you must find 2 files in csgo directory. (here -> Counter-Strike Global Offensive\csgo\resource\overviews)
For example, If you want to add blacksite you have to find dz_blacksite.txt and dz_blacksite_radar.dds. From the txt file copy 3 values (pos_x, pos_y, scale) and paste them into the table located in map.lua in the same format as the previous ones.
Your last step would be to convert dz_blacksite_radar.dds into PNG file and put it into "static" folder. Remember to name the PNG file the same as the map name you used in the map.lua table.

![image](https://github.com/HITMANek210/Aimware-Online-Radar/assets/62262011/f5a1070b-cca8-44f3-b712-d3c1302bc65b)

**Comment by HITMANek210** [comment]
I don't think this will work very well. The script is meant to be used on much smaller maps.
