### ISSUE TITLE
Uncaught TypeError: ctx.reset is not a function     at Draw ((index):42)     at (index):74

### ISSUE THREAD

**Issue by qq1364416761** [HITMANek210/Aimware-Online-Radar#3]
When I configure the project,
Safari debugging: Uncaught TypeError: ctx.reset is not a function
     at Draw ((index):42)
     at (index):74
chrome: everything works fine

**Comment by HITMANek210** [comment]
Weird, everything should work fine. I have tested the application on multiple browsers and everything worked properly. 
Check if you are using the most recent version of the browser.

**Comment by qq1364416761** [comment]
> Weird, everything should work fine. I have tested the application on multiple browsers and everything worked properly. Check if you are using the most recent version of the browser.

Seems to be some issue with browser compatibility of reset().
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/reset

**Comment by HITMANek210** [comment]
I'll see what I can do about that but for now the issue is closed.
