### ISSUE TITLE
不生效

### ISSUE THREAD

**Issue by Binshifter** [HITMANek210/Aimware-Online-Radar#4]
![image](https://user-images.githubusercontent.com/55234098/214272143-de0a708d-42e7-4396-854b-b0e391b32f71.png)
我yong用这一份配置在aw中启用了map.lua 服务端打开能够看到default的页面 但是并不能看到敌方的位置 一直保持如此
![image](https://user-images.githubusercontent.com/55234098/214272317-47f16273-70bb-41c9-a88b-52b3205c31ef.png)
q请问该如何解决这个问题

**Comment by Binshifter** [comment]
![image](https://user-images.githubusercontent.com/55234098/214275861-8c5791ed-b702-45c4-b2ac-e930df9726bd.png)


AW启用图

**Comment by HITMANek210** [comment]
Did you follow the [Installation guide](https://github.com/HITMANek210/Aimware-Online-Radar#installation-commands)?
Also make sure you allow internet connections from scripts.
![image](https://user-images.githubusercontent.com/62262011/214318864-91309ece-a2d5-4c90-a4c4-23bf8208ea94.png)
