### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ShirokoLEET** [HITMANek210/Aimware-Online-Radar#9]
When I load lua and open the website,I can only see the default.png on html.Does not show any errors in both python or aimware.
Using:Python 3.8
Aimware 5.1.1.4(already allowed internet connections from script)

**Comment by HITMANek210** [comment]
It probably means that something is blocking the requests. 
You can try to turn off the firewall on your server.
Also make sure the password set in both files (flaskapp.py, map.lua) is the same.

**Comment by ShirokoLEET** [comment]
however,i tried to I tried to put the data directly into the html and py file, it doesn't work either

**Comment by HITMANek210** [comment]
Well, that's weird. Do you have the latest version of the script? If not delete the one that you are using and clone the newest one from the repository.
